### ISSUE TITLE
Does split mode work with manually provided centers? 

### ISSUE THREAD

**Issue by sjmgarnier** [azureblue/cec#6]
However hard I try, it doesn't look like the split mode works when manually providing initial centers. I looked in the code but could not figure out where that was prevented. Any tip for making this happen?

**Comment by azureblue** [comment]
Sorry for the late answer. It should work just as good with fixed initial centers.

Can you provide the dataset and the way you called the cec on it?

I'll be happy to debug it and help.

**Comment by sjmgarnier** [comment]
@azureblue You are correct. As I was trying to create a reprex to reply to you, it worked. It must be something with my data set. I ended up creating my own splitting routine anyway, so it's all good. Sorry for the bother and thanks for this very nice package.

**Comment by azureblue** [comment]
No worries :). 

Btw. one thing that comes to my mind is `card.min` parameter (default 5%) that can prevent clusters from splitting (actually preventing creation of new small clusters).

**Comment by sjmgarnier** [comment]
@azureblue I don't think that is the issue. I set `card.min  = 0` for the purpose of my project.

**Comment by azureblue** [comment]
Ok. (`card.min` is actually set to the dimension of data + 1 minimum (needed, so that the covariance matrices have certain properties)). Anyway, there could be other reasons for the cluster not to split as expected.

PS. I let myself to look the Swarm Lab up. Very interesting stuff. Do you also do something related to simulation of flocking behavior (especially humans) in real time? For example moving group of ants/people avoiding obstacles.

**Comment by sjmgarnier** [comment]
@sjmgarnier Yes, I have done stuff like that on humans and ants indeed :-)

**Comment by sjmgarnier** [comment]
@azureblue I think that part of the issue comes from the fact that I'm dealing with non-Gaussian clusters. If I understand correctly, `cec` is clustering data points if they belong to the same multi-variate normal distribution. Here, I'm trying to use `cec` to cluster pixels in a segmented image that belongs to the same ellipsoid(-ish) objects. So I'm dealing with regularly distributed data points (dense x and y coordinates on an integer grid) and I wonder if that is what's causing the issue with the auto-splitting feature.

**Comment by azureblue** [comment]
That's probably the case. Since the CEC uses Gaussians as a model (GMM), it doesn't perform great on uniformly distributed points. When it comes to pixels, there are density based clustering algorithms (like dbscan) also you could probably use some from graph theory or just some image algorithms.  But guessing that your objects in the segmented image that you try to discover are not separated from each other, those approaches may not work well. If you know the shape of the elipsoids cec fixed covariance or fixed eigenvalues may work or some edge detection (like Canny) + Hough transform.

**Comment by sjmgarnier** [comment]
@azureblue I just created my own splitting method after applying `cec` to the data. It works well enough, so I'll stick to it for now. As you suspected, density-based clustering methods all fail as soon as two objects touch each other. Edge detection + Hough only works ok for circular objects, unfortunately.

**Comment by azureblue** [comment]
Cool :). I'm just outputting my random thoughts (more for the mental exercise), you can totally ignore them. If you're using segmented (binary) image you could probably preprocess it (like blurring) and map the gray level to "density" of points to create gaussian-like structures ((in R), by randomly removing some amount from areas depending on gray level). Then cec should feel like at home :).

**Comment by sjmgarnier** [comment]
@azureblue Coming back to that. I just noticed that you also published a paper on uniform cross-entropy clustering. Any chance for this to be implemented in the package?

**Comment by azureblue** [comment]
Currently I don't actively work with the current CEC team and wasn't involved in UCEC, for that matter. I don't know if they're going to make a package. 

That being said, I can ask them, and maybe even work on this, since it looks like a very useful CEC variant...

**Comment by sjmgarnier** [comment]
@azureblue Since @przem85 is a contributor here, I assumed that you were the other author :-) 

That would be great if someone could include this in the package but no worries if it's not soon, I know how time-consuming this can get. Cheers!
